title: Iramar Junior
description: Site pessoal feito com Jekyll
url: "https://iramarjunior.github.io"
baseurl: ""
lang: pt-BR

exclude:
  - .bundle
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
